= go-getoptions
David Gamba, https://github.com/DavidGamba
:version: 0.1
:idprefix:
:name: go-getoptions
:toc: macro

Go option parser inspired on the flexibility of Perl’s GetOpt::Long.

This REAMDE is WIP. Please review the link:http://godoc.org/github.com/davidgamba/go-getoptions[godoc] for the most up to date information.

image:https://godoc.org/github.com/davidgamba/go-getoptions?status.svg[link="http://godoc.org/github.com/davidgamba/go-getoptions"]
image:https://travis-ci.org/DavidGamba/go-getoptions.svg["Build Status", link="https://travis-ci.org/DavidGamba/go-getoptions"]

toc::[]

== Introduction

Option parsing is the act of taking command line arguments and converting them into meaningful structures within the program.

An option parser should support, at least, the following:

Boolean options::
`True` when passed on the command line.
For example:
+
`ls --all`

Options with String arguments::
The option will accept a string argument.
For example:
+
`grepp --ignore .txt`
+
Additionally, arguments to options can be passed with the `=` symbol.
+
`grepp --ignore=.txt`

The features listed above are enough to create basic programs but an option parser should do better:

Options with Integer arguments::
Parse an option string argument into an Integer and provide an user error if the string provided is not an integer.
For example:
+
`grepp --contex-lines 3`
+
and:
+
`grepp --context-lines string`
+
  Error: 'string' is not a valid integer.

Options with Floating point arguments::
Parse an option string argument into a Floating point value and provide an user error if the string provided is not a valid floating point.
For example:
+
`command --approximation 3.5`
+
and:
+
`command --approximation string`
+
  Error: 'string' is not a valid floating point value.

The features listed above relieve the programmer from the cumbersome task of converting the option argument into the expected type.

Another feature a better option parser should have is the ability to set a flag to `False`.

Negatable boolean options::
`True` when passed on the command line without any modifier and `False` when the `--no-` modifier is prefixed.
For example:
+
`command --verbose`
+
and:
+
`command --no-verbose`, or `command --noverbose`

That covers the most basic set of features, but still it is not enough to get past a basic program.
The following features will allow for a more complete interface.

Options with array arguments::
This allows the same option to be used multiple times with different arguments.
The list of arguments will be saved into an Array like structure inside the program.
For example:
+
`list-files --exclude .txt --exclude .html --exclude .pdf`

Options with Key Value arguments::
This allows the same option to be used multiple times with arguments of key value type.
For example:
+
`rpmbuild --define name=myrpm --define version=123`

Both features above should support the basic types listed before: string, integer and floating point.

The features above are useful when you have a variable amount of arguments, but it becomes cumbersome for the user when the number of entries is always the same.
The features described below and meant to handle the cases when each option has a known number of multiple entries.

Options with array arguments and multiple entries::
This allows the user to save typing.
For example:
+
Instead of writting: `color --r 10 --g 20 --b 30 --next-option` or `color --rgb 10 --rgb 20 --rgb 30 --next-option`
+
The input could be: `color --rgb 10 20 30 --next-option`

Options with key value arguments and multiple entries::
This allows the user to save typing.
For example:
+
Instead of writing: `connection --server hostname=serverIP --server port=123 --client hostname=localhost --client port=456`
+
The input could be: `connection --server hostname=serverIP port=123 --client hostname=localhost port=456`

That covers a complete user interface that is flexible enough to accommodate most programs.
The following are advanced features:

Stop parsing options when `--` is passed::
Useful when arguments start with dash `-` and you don't want them interpreted as options.

Allow passing options and non-options in any order::
Some option parsers force you to put the options before or after the arguments.
That is really annoying!

Allow pass through::
Have an option to pass through unmatched options.
Useful when writing programs with multiple options depending on the main arguments.
The initial parser will only capture the help or global options and pass through everything else.
Additional argument parsing calls are invoked on the remaining arguments based on the initial input.

Fail on unknown::
The opposite of the above option.
Useful if you want to ensure there are no input mistakes and force the application to stop.

Warn on unknown::
Less strict parsing of options.
This will warn the user that the option used is not a valid option but it will not stop the rest of the program.

Option aliases::
Options should be allowed to have different aliases.
For example, the same option could be invoked with `--address` or `--hostname`.

Incremental option::
Some options can be passed more than once to increment an internal counter.
For example:
+
`command --v --v --v`
+
Could increase the verbosity level each time the option is passed.

Additional types::
The option parser could provide converters to additional types.
The disadvantage of providing non basic types is that the option parser grows in size.

Options with optional arguments::
If the argument is not passed, the option will set the default value for the option type.
For this feature to be fully effective in strong typed languages where types have defaults, there must be a means to query the option parser to determine whether or not the option was called or not.

Option flags that call a method internally::
If all the flag is doing is call a method or function when present, then having a way to call that function directly saves the programmer some time.

Notice how so far only long options (options starting with double dash `--`) have been mentioned.
There are 3 main ways to handle short options (options starting with only one dash `-`), see the <<operation_modes>> section for details.

[[operation_modes]]
== Operation Modes

The behaviour for long options (options starting with double dash `--`) is consistent across operation modes.
The behaviour for short options (options starting with only one dash `-`) depends on the _operation mode_.
The sections below show the different operation modes.

=== Normal Mode (default)

|===
|Given argument |Interpretation

|--opt
a|option: `"opt"`,  argument: `nil`

|--opt=arg
a|option: `"opt"`, argument: `"arg"` footnote:[Argument gets type casted depending on option definition.]

|-opt
a|option: `"opt"`, argument: `nil`

|-opt=arg
a|option: `"opt"`, argument: `"arg"` footnote:[Argument gets type casted depending on option definition.]

|===

=== Bundling Mode

Set by defining `{mode: "bundling"}` in the options hash.

|===
|Given option |Interpretation

|--opt
a|option: `"opt"`,  argument: `nil`

|--opt=arg
a|option: `"opt"`, argument: `"arg"` footnote:[Argument gets type casted depending on option definition.]

|-opt
a|option: `"o"`, argument: `nil` +
option: `"p"`, argument: `nil` +
option: `"t"`, argument: `nil`

|-opt=arg
a|option: `"o"`, argument: `nil` +
option: `"p"`, argument: `nil` +
option: `"t"`, argument: `"arg"` footnote:[Argument gets type casted depending on option definition.]

|===

=== Enforce Single Dash Mode

Set by defining `{mode: "enforce_single_dash"}` or `{mode: "single_dash"}` in the options hash.

|===
|Given option |Interpretation

|--opt
a|option: `"opt"`,  argument: `nil`

|--opt=arg
a|option: `"opt"`, argument: `"arg"` footnote:[Argument gets type casted depending on option definition.]

|-opt
a|option: `"o"`, argument: `"pt"` footnote:[Argument gets type casted depending on option definition.]

|-opt=arg
a|option: `"o"`, argument: `"pt=arg"` footnote:[Argument gets type casted depending on option definition.]

|===

== Biggest option parser misfeature - Automatically generate help

The biggest misfeature an option parser can have is to automatically generate the help message for the programmer.
This seemingly helpful feature has caused most scripts not to have proper man pages anymore and to have all options descriptions mixed in the help synopsis.

Don't be lazy, write a man page for your program and create the program's synopsis yourself.

== Quick overview

. Define your command line specification:
+
[source,go,subs=attributes]
----
import "github.com/davidgamba/go-getoptions" // As getoptions

opt := getoptions.GetOptions()
b := opt.Bool("flag", false)
s := opt.String("string", "")
i := opt.Int("int")
remaining, err := opt.Parse(os.Args[1:])

if *b {
  // ... do something
}

if opt.Called["int"] {
  // ... do something with i
}
----

. Pass cmdline arguments:
+
----
$ ./myscript non-option -f --string=mystring -i 7 --float 3.14 --p --version non-option2 -- --nothing
----

. Internally it will return an array with the arguments that are not options and anything after the `--` identifier, and a Map with the values of the options that were passed.

== Features

* Support for `--long` options.

* Support for short (`-s`) options with flexible behaviour:

  - Normal (default)
  - Bundling
  - SingleDash

* Supports passing `--` to stop parsing arguments (everything after will be left in the `remaining []string`).

* Multiple aliases for the same option. e.g. `help`, `man`.

* Multiple argument types.

* Supports both Array and Key Value options.

* Supports command line options with '='.
For example: You can use `--string=mystring` and `--string mystring`.

* opt.Called indicates if the parameter was passed on the command line.

== How to install it

. Get it from github:
+
`go get github.com/davidgamba/go-getoptions`

. Then import it:
+
`import "github.com/davidgamba/go-getoptions" // As getoptions`

. Enjoy!

== Dependencies

Go 1.5+

[[roadmap]]
== Roadmap

* All other Perl's Getopt::Long goodies that seem reasonable to add!

== License

This file is part of go-getoptions.

Copyright (C) 2015-2016  David Gamba Rios

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
